spring:
  application:
    name: Angjiax-ai-gent
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/agent
    username: root
  profiles:
    active: local
  ai:
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
#  ai:
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        distance-type: COSINE_DISTANCE
#        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch



server:
  port: 8123
  servlet:
    context-path: /api

mybatis-plus:
  configuration:
    #MyBatis配置
    map-underscore-to-camel-case: false
    #仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete #全局逻辑删除的实体字段名
      logic-delete-value: 1 #逻辑已删除默认值
      logic-not-delete-value: 0 #逻辑未删除默认值

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.angjiax.angjiaxaigent.controller
# knife4j???????????????
knife4j:
  enable: false
  setting:
    language: zh_cn

#logging:
#  level:
#    org.springframework.ai: DEBUG
